# default config.yml for MysqlInventoryBridge
# config version 1.4.3

#MySQL Database details
database:
    mysql:
        #MySQL server address
        host: 127.0.0.1
        #MySQL server port (default 3306)
        port: 3306
        #Database name (NOTE! You need to create the database, then the plugin will create the tables.)
        databaseName: 'mydatabase'
        #Tables name (the plugin will auto create it)
        tableName: 'meb_inventory'
        #User name
        user: 'admin'
        #User password
        password: 'cheesecake'
    #Remove inactive users from the database. This maintenance task will start each server start with a 2min delay.
    maintenance:
        #Enable or disable database maintenance.  | (true or false)
        enabled: false
        #Inactivity in days. Default 60 days.
        inactivity: 60
        
        
#Other configurable options
General:
    #Login economy sync delay in milliseconds (default 1000 milliseconds = 1 second)
    #This delay is needed in bungeecord setups, because when you move between servers the quit and login takes place almost in the same time.
    loginSyncDelay: 1000
    #Set this to false to disable the sync of players armor. |  (true or false)
    syncArmorEnabled: true
    #Disable clear of inventory and armor after data is uploaded to mysql.
    disableItemClear: false
    #Enable modded items support. This will require the ProtocolLib dependency! |  (true or false)
    #This is needed if you experience item data loss on some mods that save NBT data.
    #WARNING! All the servers that are in sync must have this option set the same, or you will lose items.
    enableModdedItemsSupport: false
    

#Chat Messages with full color and format codes support. Disable any message by setting it to ''  |  Example>  syncComplete: ''
#Minecraft Color and Format Codes: http://minecraft.gamepedia.com/Formatting_codes
ChatMessages:
    syncComplete: '&2[MIB] &aData sync complete!'