name: MysqlInventoryBridge
main: net.craftersland.bridge.inventory.Inv
version: 1.4.3
author: CraftersLand
website: www.craftersland.net
load: STARTUP
description: Sync players inventorys over many servers using MySQL.
softdepend: [ProtocolLib]